version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env
  web:
    build: ./backend
    command: /code/entrypoint.sh
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
